### ISSUE TITLE
Themes do not apply

### ISSUE THREAD

**Issue by cynojien** [marios8543/Deckcord#3]
First off. This plugin is fantastic! So thank you for working in it.

I went to apply a theme in the Vencord settings and nothing actually changed when applying. I tried both local CSS (applied through Big Picture in Desktop mode as gamescope doesn't provide a file picker) and using the via link option.

Is this something that might be added later on?

Thanks again.

**Comment by marios8543** [comment]
ah yea i think some of the vencord stuff is broken i think, I'll look into it
