### ISSUE TITLE
Can’t get past “Initializing”

### ISSUE THREAD

**Issue by calvincorrieri** [marios8543/Deckcord#4]
I’ve tried reinstalling and reloading the plugin, but it just says “initializing” even after I left it for ten minutes. Is there some step that I’m missing here, or is it just broken?

**Comment by calvincorrieri** [comment]
Side note: when I reload the plugin, the keyboard pops up, but just the keyboard. No login screen or anything.

Also, I can open the discord tab created by the plugin but that is also blank.

**Comment by CBozsik** [comment]
I'm experiencing the exact same issue. Fresh install of Deckcord and stuck on "Initalizing..." and the keyboard popped up in the background.

**Comment by squizzi** [comment]
I was able to work around this by installing a `0.2.4` version, signing into Discord and then updating to the latest `0.2.6` commit.  My guess is there's a regression in the initialization code which adds the Discord panel onto the Steam button menu in the latest version.

**Comment by CBozsik** [comment]
> I was able to work around this by installing a `0.2.4` version, signing into Discord and then updating to the latest `0.2.6` commit. My guess is there's a regression in the initialization code which adds the Discord panel onto the Steam button menu in the latest version.

Thanks! Installing the latest 0.2.4 version let me sign in, and then updating to 0.2.6 retains access. Good workaround until the creator can update to resolve the login issues.

**Comment by BarterClub** [comment]
> I was able to work around this by installing a `0.2.4` version, signing into Discord and then updating to the latest `0.2.6` commit.  My guess is there's a regression in the initialization code which adds the Discord panel onto the Steam button menu in the latest version.

Can confirm. 2.4 works.

**Comment by marios8543** [comment]
This bug should be fixed on latest version (0.3.1)

**Comment by flynnisthename** [comment]
Doesn’t work in latest versions
