### ISSUE TITLE
The stream has a very low brightness

### ISSUE THREAD

**Issue by nyackq** [marios8543/Deckcord#9]
I installed Deckcord today and noticed that the picture of the stream is much darker than on the steamdeck
Display Deck:
![hades_disc_deck](https://github.com/marios8543/Deckcord/assets/156529661/46bd58fd-a954-4661-90fc-8de14592e478)
Display Stream (watched on the pc):
![hades_disc_pc](https://github.com/marios8543/Deckcord/assets/156529661/5f2550b0-6689-4dcb-badc-15e5901b9926)

**Comment by marios8543** [comment]
Yea it's a Steam issue. I'm not sure what's causing it but other plugins that do screen capture also have it, and steam remote play also has it. Idk what's causing it and how to fix it sorry
